version: '3.7'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - db:/var/libmysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=rocketseat-db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - exemple

  api-reacket:
    build:
      context: .
    container_name: api-rocketseat
    ports:
      - 30001:3000
    depends_on:
      - mysql
    networks:
      - exemple

networks:
  exemple:
    name: exemple
    external: true
    driver: bridge

volumes:
  db:
